apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-ks
rules:
  - apiGroups:
      - "kustomize.toolkit.fluxcd.io"
    verbs:
      - "*"
    resources:
      - "kustomizations"
