apiVersion: v1
kind: Secret
metadata:
  name: github
stringData:
  secret: ENC[AES256_GCM,data:AMM2YzeMipWcYnodJS3U8+2fhkryXC6ArALNxFY62vG411439pIviIP1fUaYY+H9bUTOo4MihfEao0xyQX1qS/N9gaIjWyyGhM3uyNaqdxaCsM9VmAx4jtWFHhK9OXsRRYC4owIO,iv:nhI2K8JONXkJXAMzRJpZLT7gyt2myx3Z/fpWsBNd5AY=,tag:viJ5zM0aY42Hnbtl9fQNLg==,type:str]
  token: ENC[AES256_GCM,data:4+TCxAUy2zmyAC2YyfBvBbwqKfoK2uhwaCxTwxRp6Plrb4F3E4VkCQ==,iv:6Q4EoWkUX58QzFqup2BzGl7gzVvvwGPHbyR/vNxfWng=,tag:mTDt7DSH3t89JlB14pPojg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-09-20T23:54:06Z"
  mac: ENC[AES256_GCM,data:RUZ7MNp8ucY0Nbx8RwyycIxzQ+ybg0PNIdM+fu6QYcsJF2wDXH7I5LCOIfGNJi41P3qb9qzXtcmN4xokL/yhgTSgecYe8dJO0z7X6jC9EhSSX3jv1P6XNLhZqdYe9/aXgpkKwYqKGsoSt0UgtZ2B0LiwU5hyT2z+787GzUQ3yF4=,iv:NVfD5IXJ8Fa6N9lBTZYOXGQxM50QWN/YknNtH6ilDb8=,tag:1bSS8Aqj5/XYG4qfXRRctA==,type:str]
  pgp:
    - created_at: "2023-09-20T23:54:06Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxb3go410o2rARAAl97lXAwvgPmRgV6vt04yoNreJvhJkV1klRsxjFxM8k0X
        fRwRmXZ7R9/+/jNl/W/VShh/g4MuFuKH7HF0ZraS6dwaqirgLlWOAFgTKBi3iUrx
        TtOZOIFfQVu84oqdiOfQ82HXQ2wrwnqItVWTTrlF7I2tmBX7EI7klCSu0PLOdxw8
        LLRKqMFfjC0ZOirW3wwsyUDRw7vLfJrKAd1PwCjq8Lc/Ov9XysTWgkQQmh12hWCZ
        inKzQQXB8cUlU2MD7VVR8Dp9LErGalnNYRkiCMYacNVQ+U8YjYCDVRZcjNBjKEaT
        fQBM8AvQ2zWyxx4nwpM8AJshSqt17UWBAJQMxZA5ImhSeNSNSXm7KNF/3Zk8bYBA
        EWc3W3iFYqtwMjv8Kzp0bcooFXlO2tegIfz1T8P3pqOPUcAl3S9g59Y3keRJSbVl
        wh+JOQw8XElKv2hm0h/TFrKq3itJqekM9qWy9aEo94TYbGIibvG2gjBpI29NjF5P
        ErYlbv/vHqSrg+QggmbZFp/UWOJpJjLIcbpoi36u0VFwU8neyKdS1pbpUDRqV1W3
        ul1t2GCLDbkjdPZ5jqK/8x/q0RbFUd+SM1yOwU6OEvq4joQzLHpLfQssFotQ6Nqv
        Yf8xL1e4Uqu0XBKH6DEsm2Bk87Is5WzbIGc3iueZNnyeb/sAvhpty/JNYQLbWEXU
        aAEJAhAMoRGecHFvmDBXl5OmVcAVgnr2qp9iCZYHMrddbVliyACu3908pOW8waRr
        f+PJFJE1CqTizrq9YZrZFUW+z1KI1MkHeS508vgQOen3cUzIub0xcKObohaO+NJU
        No6+lZazRNrw
        =us0A
        -----END PGP MESSAGE-----
      fp: F3E1BB9F523C44DBEFA4485842B95257909D72BD
  encrypted_regex: ^(data|stringData)$
  version: 3.8.0
