apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argo-events
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/resources/argo/events
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
