apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argo-events
spec:
  interval: 10m
  path: ./flux/resources/argo/events
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
