apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoyproxy-gateway-class
spec:
  interval: 10m
  path: ./flux/resources/envoy/class
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  # dependsOn:
  #   - name: envoyproxy-gateway-operator
