apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoyproxy-gateway-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/resources/envoy/gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
