apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: greater
spec:
  interval: 10m
  path: ./flux/projects/greater
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      env: production
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
