apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - argo-events.yaml
  - argo-github.yaml
  - envoy-gataway-class.yaml
  - envoy-gataway-operator.yaml
  - greater.yaml
