apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: envoyproxy-gateway
spec:
  releaseName: envoyproxy-gateway
  chart:
    spec:
      chart: gateway-helm
      sourceRef:
        kind: HelmRepository
        name: envoyproxy-gateway
      version: "v0.5.0"
  interval: 10m
  values: {}
